CSI-3069: Add bash to alpine images + fix missing webp support for gd
MyOnlineStore/docker-php-dev pull request #19
Opened 2022-01-17 12:11 UTC by koenvdheuvel

Builds locally

2022-01-17 12:59 UTC, steven166 requested changes

2022-01-17 12:59 UTC, steven166 commented on Dockerfile-alpine.template
> +RUN --mount=type=cache,target=/var/cache/apk \
I don't think it is a good practice to cache the apk repository

2022-01-17 14:32 UTC, koenvdheuvel commented on Dockerfile-alpine.template
> +RUN --mount=type=cache,target=/var/cache/apk \
This will help speed up future builds. We do this with the monolith image aswell

2022-01-17 14:45 UTC, steven166 commented on Dockerfile-alpine.template
> +RUN --mount=type=cache,target=/var/cache/apk \
I think that is a bad path to go. The remote repository should be the source of truth, as it will be regularly updated with security patches. It will also result in strange behavior if the base images get updated suddenly, but the repo list not.  
And the apt package list of alpine isn't that big, so it only takes seconds too download.

2022-01-19 10:49 UTC, koenvdheuvel commented on Dockerfile-alpine.template
> +RUN --mount=type=cache,target=/var/cache/apk \
Don't we still need a `apk update` then so that we are sure to force the update of the package list so the latest versions get installed? 

If the same versions of packages get installed we can utilize the buildkit cache and that we we are sure that we are always up to date when a image gets built.

2022-01-19 11:00 UTC, tmakel commented on Dockerfile-alpine.template
> +RUN --mount=type=cache,target=/var/cache/apk \
Just my 2 cents: I must admit I lack the knowledge the exact implications of this and more or less see it as an experiment. However, if the speed gains are marginal but could cause flaky behaviour, I think it's probably better to omit this.

2022-01-28 11:24 UTC, koenvdheuvel commented on Dockerfile-alpine.template
> +RUN --mount=type=cache,target=/var/cache/apk \
Removed the caching

2022-01-31 13:41 UTC, frankverhoeven approved these changes

2022-02-02 13:14 UTC, steven166 approved these changes

2022-02-03 11:10 UTC, merged